[login_infos]
password="bar"

[screen_infos]
# Commun
line_height = 45
parsing_height = 25

# open_rune_shop
brak_rune_x = 1084
brak_rune_y = 462
rune_box_x = 382
rune_box_y = 431

# get_start_y
start_y = 218

# end_of_scroll
x_pixel = 1207
y_pixel = 838

# ressource_click
rc_min_x = 670
rc_max_x = 900
rc_min_y = 210
rc_max_y = 250

# null_click
nc_min_x = 355
nc_max_x = 1175
nc_min_y = 35
nc_max_y = 95

# name_treatment
name_start_x = 667
name_width = 232

# mid_price_treatment
mid_price_start_x = 1070
mid_price_width = 100

# lot_number_treatment
lot_number_start_x = 830
lot_number_width = 70

# lot_price_treatment
lot_price_start_x = 940
lot_price_width = 80

[db_infos]
db_path = 'Z'
