[screen_infos]
# Commun
line_height = 45
parsing_height = 25

# ready_to_laucnh
start_button_x = 325
start_button_y = 515
start_button_width = 85
start_button_height = 35

# in_brakmar
brak_pos_x = 10
brak_pos_y = 42
brak_pos_width = 100
brak_pos_height = 32

# in_rune_shop
rune_pos_x = 395
rune_pos_y = 415
rune_pos_width = 135
rune_pos_height = 30

# open_rune_shop
brak_rune_x = 1084
brak_rune_y = 462
rune_box_x = 382
rune_box_y = 431

# get_start_y
start_y = 218

# end_of_scroll
x_pixel = 1207
y_pixel = 838

# ressource_click
rc_min_x = 670
rc_max_x = 900
rc_min_y = 210
rc_max_y = 250

# null_click
nc_min_x = 355
nc_max_x = 1175
nc_min_y = 35
nc_max_y = 95

# name_treatment
name_start_x = 667
name_width = 232

# mid_price_treatment
mid_price_start_x = 1070
mid_price_width = 100

# lot_number_treatment
lot_number_start_x = 830
lot_number_width = 70

# lot_price_treatment
lot_price_start_x = 940
lot_price_width = 80

# is_clicked
buy_button_x = 1090
buy_button_width = 65

[tempo_infos]
# Commun
quick_tempo = 0.5
test_tempo = 0

# window
init_tempo = 1
launch_tempo = 3
char_tempo = 8
log_tempo = 19

# desktop
mouse_tempo = 0.1

# bot_dofus
lag_tempo = 1

[db_infos]
db_path = 'dofus-trading.csv'
