[login_infos]
password="foo"

[screen_infos]
# Commun
line_height = 46
parsing_height = 25

# open_rune_shop
brak_rune_x = 1086
brak_rune_y = 460
rune_box_x = 370
rune_box_y = 430

# get_start_y
start_y = 215

# end_of_scroll
x_pixel = 1210
y_pixel = 845

# ressource_click
rc_min_x = 665
rc_max_x = 890
rc_min_y = 210
rc_max_y = 245

# null_click
nc_min_x = 350
nc_max_x = 1180
nc_min_y = 30
nc_max_y = 95

# name_treatment
name_start_x = 665
name_width = 235

# mid_price_treatment
mid_price_start_x = 1070
mid_price_width = 100

# lot_number_treatment
lot_number_start_x = 830
lot_number_width = 70

# lot_price_treatment
lot_price_start_x = 940
lot_price_width = 80

[tempo_infos]
# Commun
quick_tempo = 0.5

# window
init_tempo = 0.8
launch_tempo = 17
char_tempo = 8
log_tempo = 19
shop_tempo = 2

# desktop
mouse_tempo = 0.1

# bot_dofus
lag_tempo = 0.3
scroll_tempo = 1

[db_infos]
db_path = 'dofus-trading.csv'
